name: Enpal Wallbox Controller
version: "1.0.6"
slug: enpal_wallbox_controller
description: REST API zur Steuerung der Enpal Wallbox.
startup: services
boot: auto
options:
  base_url: "http://192.168.x.x"
schema:
  base_url: str
init: false
arch:
  - amd64
  - aarch64
  - armv7
ports:
  36725/tcp: 36725
map:
  - config:rw
