name: Generate CHANGELOG.md

on:
  release:
    types: [published]

jobs:
  generate-changelog:
    name: Generate CHANGELOG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install github_changelog_generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG.md
        run: |
          github_changelog_generator \
            --user derolli1976 \
            --project enpal-wallbox-addon \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --output enpal_wallbox_controller/CHANGELOG.md \
            --no-verbose

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-update CHANGELOG.md"
          branch: changelog/update-${{ github.run_number }}
          title: "Update CHANGELOG.md from latest release"
          body: "This pull request was automatically generated after a new release."
          base: main
